# Generated by Django 4.0.4 on 2022-05-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
