# Generated by Django 4.0.4 on 2022-05-20 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_about_created_at_alter_about_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
