# Generated by Django 4.0.4 on 2022-05-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_about_updated_at_alter_about_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
