# Generated by Django 4.0.4 on 2022-05-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_about_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
