# Generated by Django 4.0.4 on 2022-05-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_about_created_at_alter_about_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.TextField(),
        ),
    ]
