# Generated by Django 4.0.4 on 2022-05-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_about_profile_pic_alter_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(upload_to='projects'),
        ),
    ]
