# Generated by Django 4.0.4 on 2022-05-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_about_profile_pic_alter_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='exec_control',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='hidden',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
    ]
