# Generated by Django 4.0.4 on 2022-05-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_about_profile_pic_alter_admin_exec_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='exec_control',
            field=models.BooleanField(),
        ),
    ]
