# Generated by Django 4.0.4 on 2022-05-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_admin_exec_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business_name',
            field=models.TextField(blank=True),
        ),
    ]
