# Generated by Django 4.0.4 on 2022-05-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_admin_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_path',
            field=models.TextField(blank=True),
        ),
    ]
