# Generated by Django 4.0.4 on 2022-05-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_invoice_invoice_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_label',
            field=models.FileField(upload_to='invoices_folder'),
        ),
    ]
