# Generated by Django 4.0.4 on 2022-06-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_invoice_invoice_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_path',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_label',
            field=models.FileField(blank=True, upload_to='invoices_folder'),
        ),
    ]
