# Generated by Django 4.0.4 on 2022-06-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_invoice_invoice_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_location',
            field=models.FileField(blank=True, upload_to='invoices_folder'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_label',
            field=models.TextField(blank=True),
        ),
    ]
